GET http://localhost:8080/cookies/firefox
Authorization: Basic user password

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

http://localhost:8080
Authorization: Basic admin password

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###
